apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - moldavite.yaml
  - moldavite-imagestream.yaml
  - moldavite-route.yaml
  - moldavite-service.yaml
  - moldavite-rbac.yaml
  - moldavite-configmap.yaml
  - moldavite-jupyterbook-build.yaml
  - moldavite-jupyterhub-build.yaml
  - argo-deployments.yaml
  - argo-imagestreams.yaml
  - argo-management.yaml
  - argo-ui-controller.yaml
  - argo-workflow-controller.yaml
